# Gokapi URL: https://github.com/Forceu/Gokapi

# Cloudflare-Tunnel: 
# https://one.dash.cloudflare.com/ > Login > Access > Tunnels > "Create Tunnel" > get "--token" == mytokengoeshere
# Once this is done, Cloudflare automaticly configures the CNAME linked with the proxied Tunnel

name: gokapi-stack

services:
  gokapi:
    image: f0rc3/gokapi:latest
    container_name: Gokapi-Cloudflared
    volumes:
      - ./conf:/app/config
      - ./data:/app/data
    environment:
      - GOKAPI_USERNAME=${gokapi_username}
      - GOKAPI_PASSWORD=${gokapi_password}
      - GOKAPI_PORT=53842
      - GOKAPI_EXTERNAL_URL=https://subdomain.domain.de
      - GOKAPI_REDIRECT_URL=https://github.com/Ali333n
      - GOKAPI_LOCALHOST=no
      - GOKAPI_USE_SSL=no
    networks:
      - nginx-proxy-manager_ntwk
      - internal
    restart: unless-stopped
    expose:
      - '53842'

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: Gokapi-Cloudflared-Tunnel
    environment:
      - TUNNEL_TOKEN=${tunnel_token}
    networks:
      - internal
    command: tunnel run
    restart: unless-stopped

networks:
  nginx-proxy-manager_ntwk:
    external: true

  internal:
    driver: bridge
