# Gokapi URL: https://github.com/Forceu/Gokapi

# Cloudflare-Tunnel: 
# https://one.dash.cloudflare.com/ > Login > Access > Tunnels > "Create Tunnel" > get "--token" == mytokengoeshere
# Once this is done, Cloudflare automaticly configures the CNAME linked with the proxied Tunnel

services:
  gokapi:
    container_name: Gokapi-Cloudflared
    image: f0rc3/gokapi:latest
    ports:
      - 53842:53842
    environment:
      - GOKAPI_USERNAME=${gokapi_username}
      - GOKAPI_PASSWORD=${gokapi_password}
      - GOKAPI_PORT=53842
      - GOKAPI_EXTERNAL_URL=https://subdomain.domain.de
      - GOKAPI_REDIRECT_URL=https://github.com/Ali333n
      - GOKAPI_LOCALHOST=no
      - GOKAPI_USE_SSL=no
    volumes:
      - ./gokapi/conf:/app/config
      - ./gokapi/data:/app/data
    restart: unless-stopped
    networks:
     - nginx-proxy-manager_ntwk
     - internal

  tunnel:
    container_name: Gokapi-Cloudflared-Tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${tunnel_token}
    networks:
     - internal

networks:
  nginx-proxy-manager_ntwk:
    external: true

  internal:
    driver: bridge