# https://docs.portainer.io/start/install-ce/server/docker/linux

name: portainer-project

services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=portainer.${DOMAIN}
      - VIRTUAL_PORT=9000
    ports:
      - "8000:8000"
    expose:
      - "9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data

volumes:
  data:

networks:
  nginx-proxy-manager_ntwk:
    external: true