# https://nginxproxymanager.com/setup/
# https://docker-compose.de/en/proxy/nginx-proxy-manager/

services:
  app:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    environment:
      DISABLE_IPV6: true
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    networks:
      - ntwk
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "/usr/bin/check-health" ]
      interval: 10s
      timeout: 3s

networks:
  ntwk:
    driver: bridge
