name: mealie-project

services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    volumes:
      - ./mealie-data:/app/data/
    environment:
      ALLOW_SIGNUP: "true"
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
      BASE_URL: https://${DOMAIN}
    networks:
      - nginx-proxy-manager_ntwk
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.90'
          memory: 1G
    expose:
      - '9000'

networks:
  nginx-proxy-manager_ntwk:
    external: true
