# https://github.com/CorentinTh/it-tools

name: it-tools-stack

services:
    it-tools:
      image: corentinth/it-tools:latest 
      container_name: IT-Tools-Cloudflared
      restart: unless-stopped
      expose:
        - "80"
      networks:
        - nginx-proxy-manager_ntwk
        - internal

    tunnel:
      image: cloudflare/cloudflared:latest
      container_name: IT-Tools-Cloudflared-Tunnel
      restart: unless-stopped
      command: tunnel run
      environment:
        - TUNNEL_TOKEN=${tunnel_token}
      networks:
        - internal

networks:
  nginx-proxy-manager_ntwk:
    external: true

  internal:
    driver: bridge