# https://github.com/CorentinTh/it-tools

services:
  it-tools:
    image: corentinth/it-tools:latest
    container_name: IT-Tools-Cloudflared
    networks:
      - nginx-proxy-manager_ntwk
      - internal
    restart: unless-stopped
    expose:
      - '80'

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: IT-Tools-Cloudflared-Tunnel
    environment:
      - TUNNEL_TOKEN=${tunnel_token}
    networks:
      - internal
    command: tunnel run
    restart: unless-stopped

networks:
  nginx-proxy-manager_ntwk:
    external: true

  internal:
    driver: bridge
