# https://docs.semaphoreui.com/administration-guide/installation/docker/

services:
  mysql:
    restart: unless-stopped
    image: mysql:8.0
    hostname: mysql
    volumes:
      - ./semaphore/mysql:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: ${DB_Name}
      MYSQL_USER: ${DB_User}
      MYSQL_PASSWORD: ${DB_Pass}
  semaphore:
    restart: unless-stopped
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: ${DB_Pass}
      SEMAPHORE_DB_HOST: mysql:3306
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB: ${DB_Name}
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: ${Admin_Pass}
      SEMAPHORE_ADMIN_NAME: ${Admin_Name}
      SEMAPHORE_ADMIN_EMAIL: ${Admin_Mail}
      SEMAPHORE_ADMIN: ยง{Admin_Name}
      SEMAPHORE_COOKIE_HASH: ${Cookie_Hash}                       # head -c32 /dev/urandom | base64
      SEMAPHORE_COOKIE_ENCRYPTION: ${Cookie_Encryption}           # head -c32 /dev/urandom | base64
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${Access_Key}              # head -c32 /dev/urandom | base64
      TZ: Europe/Berlin
    volumes:
      - ./semaphore/data:/var/lib/semaphore
      - ./semaphore/config:/etc/semaphore
      - ./semaphore/temp:/tmp/semaphore
    depends_on:
      - mysql

