version: "2"
services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    hostname: adguardhome
    ports:
      - 53:53/tcp
      - 80:80/tcp
      - 443:443/tcp
      - 853:853/tcp
      - 3001:3001/tcp
      - 5443:5443/tcp
      - 53:53/udp
      - 67:67/udp
      - 443:443/udp
      - 784:784/udp
      - 853:853/udp
      - 5443:5443/udp
      - 8853:8853/udp

    network_mode: "host"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    #healthcheck:
      #test: wget --no-verbose --tries=1 --spider http://localhost || exit 1
      #interval: 120s
      #retries: 5
      #start_period: 20s
      #timeout: 10s
    labels:
      - deunhealth.restart.on.unhealthy=true
    volumes:
      - /volume1/docker/adguardhome/work:/opt/adguardhome/work
      - /volume1/docker/adguardhome/conf:/opt/adguardhome/conf