# https://unpoller.com/docs/install/dockercompose
# https://unpoller.com/docs/dependencies/influxdb/#post-setup
# https://unpoller.com/docs/install/grafana/
# https://unpoller.com/docs/install/controllerlogin/

services:
  influxdb:
    image: influxdb:latest
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb-storage:/var/lib/influxdb2
      - ./influxdb-config:/etc/influxdb2
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_HTTP_AUTH_ENABLED=${INFLUXDB_HTTP_AUTH_ENABLED}
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
      - DOCKER_INFLUXDB_INIT_RETENTION=${INFLUXDB_RETENTION}
    healthcheck:
      test: [
        "CMD-SHELL",
        "curl -s -o /dev/null -w '%{http_code}' -u $${INFLUXDB_ADMIN_USER}:$${INFLUXDB_ADMIN_PASSWORD} http://localhost:8086/ping | grep -q '204'"
      ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - nginx-proxy-manager_ntwk
      - internal

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    expose:
      - "3000"
    volumes:
      - ./grafana-storage:/var/lib/grafana
    user: "1000:1000"
    depends_on:
      influxdb:
        condition: service_healthy
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-clock-panel,natel-discrete-panel,grafana-piechart-panel
    networks:
      - nginx-proxy-manager_ntwk
      - internal

  unpoller:
    image: ghcr.io/unpoller/unpoller:latest
    restart: unless-stopped
    depends_on:
      influxdb:
        condition: service_healthy
      grafana:
        condition: service_started
    environment:
      - UP_INFLUXDB_DB=${INFLUXDB_DB}
      - UP_INFLUXDB_USER=${INFLUXDB_ADMIN_USER}
      - UP_INFLUXDB_PASS=${INFLUXDB_ADMIN_PASSWORD}
      - UP_INFLUXDB_ORG=${INFLUXDB_ORG}
      - UP_INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - UP_INFLUXDB_AUTH_TOKEN=${INFLUXDB_ADMIN_TOKEN}
      - UP_INFLUXDB_URL=http://influxdb:8086
      - UP_UNIFI_DEFAULT_USER=${UNIFI_USER}
      - UP_UNIFI_DEFAULT_PASS=${UNIFI_PASS}
      - UP_UNIFI_DEFAULT_URL=${UNIFI_URL}
      - UP_POLLER_DEBUG=${POLLER_DEBUG}
      - UP_UNIFI_DEFAULT_SAVE_DPI=${POLLER_SAVE_DPI}
    networks:
      - internal # This service only communicates with other internal services (e.g., InfluxDB, Grafana) and does not require external access.

networks:
  nginx-proxy-manager_ntwk:
    external: true

  internal:
    driver: bridge