# .github/workflows/docker-compose-lint.yml
name: Docker Compose Lint

on:
  push:
    paths:
      - 'Compose/**'
  pull_request:
    paths:
      - 'Compose/**'

jobs:
  lint:
    name: Docker Compose Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up latest Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install DCLint (latest)
        run: npm install --global dclint

      - name: Run DCLint on all Compose files
        run: |
          find Compose -type f -name "docker-compose.yml" | while read -r file; do
            echo "Linting and Auto-Fixing $file"
            dclint "$file" --fix
          done

      - name: Commit and push changes if DCLint fixed files
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Automatisch alle geänderten docker-compose.yml Dateien committen und pushen
          CHANGED_FILES=$(git diff --name-only | grep '^Compose/.*docker-compose.yml$' || true)

          for file in $CHANGED_FILES; do
            PROJECT_NAME=$(echo "$file" | awk -F'/' '{print $2}')
            echo "Auto-Fixing $file for project $PROJECT_NAME"

            git add "$file"
            git commit -m "chore($PROJECT_NAME): auto-fix docker-compose.yml via DCLint"
          done

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git push origin HEAD:${{ github.ref_name }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}